/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "igoooohxtabcjruolhpi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnb29vb2h4dGFiY2pydW9saHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MzQ1NzIsImV4cCI6MjA4ODAxMDU3Mn0.9tWu-y3IvuMf3OSIE5m0J-Ywz0TE7lEjhILw472hpSI"